name: lint_and_unit_test_on_PR_to_DEV

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  Unit-test:
    name: Run static check & unit tests on PR in DEV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: Run static checks & and unit tests
        run: ./gradlew check

      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Upload test report directory
        uses: actions/upload-artifact@v2
        with:
          name: testDebugStuff
          path: app/build/reports/tests/testDebugUnitTest/
          if-no-files-found: warn
          
