name: sign_release_on_PUSH_to_main

on:
  push:
    branches:
      - 'main'
      
env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_SIGN_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_SIGN_KEY_PASSWORD }}

jobs:
  build_apk_aab:
    name: Build release artifacts
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
        
      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPOSITORY }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: app/keystore
          
      - name: Build release AAB
        run:
          ./gradlew bundleRelease
      
      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-release.aab
          path: app/build/outputs/bundle/release/app-release.aab
          
      - name: Deploy to track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{secrets.SERVICE_ACCOUNT}}
          packageName: com.r42914lg.chatsandbox
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
          
