name: smoke_test_and_tag_release_on_PR_to_main

on:
  pull_request:
    branches:
      - 'main'
      
permissions: write-all

jobs:
  smoke_test:
    if: startsWith(github.head_ref, 'release/') == true
    name: Run UI tests on PR in main
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew -Pandroid.testInstrumentationRunnerArguments.class=com.r42914lg.chatsandbox.ExampleInstrumentedTest connectedCheck
          
  tag:
    name: Smore test complete, proceeding to TAG job
    runs-on: ubuntu-latest
    needs: [smoke_test]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 11}
                    
      - name: Tag Release
        run: |
          branch_name=${GITHUB_HEAD_REF}
          version_name=${GITHUB_HEAD_REF##*/}
          echo "Head branch name: $branch_name"
          echo "Head version: $version_name"
          echo "Tagging release with tag $version_name"
          git tag $version_name
          git push origin --tags
          
