name: ui_test_on_PR_to_DEV

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  test:
    name: Run UI tests on PR in DEV
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with: {java-version: 11}
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
          
